/*
 * UPDATE_PRODUCTS:
 * - pushes new products to the end of copy of products array
 * - updates products array
 */
export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const TOGGLE_CART = "TOGGLE_CART";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
export const UPDATE_CURRENT_SUBCATEGORY = "UPDATE_CURRENT_SUBCATEGORY";

export const UPDATE_SUBCATEGORIES = "UPDATE_SUBCATEGORIES";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const ADD_MULTIPLE_TO_WISHLIST = "ADD_MULTIPLE_TO_WISHLIST";
export const UPDATE_WISHLIST = "UPDATE_WISHLIST";
export const CLEAR_WISHLIST = "CLEAR_WISHLIST";
export const CURRENT_PRODUCT = "CURRENT_PRODUCT";

export const SEARCH = "SEARCH";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
export const CLEAR_CURRENT_SUBCATEGORY = "CLEAR_CURRENT_SUBCATEGORY";
export const UPDATE_SEARCHED_PRODUCTS = "UPDATE_SEARCHED_PRODUCTS";
export const CURRENT_SUBCATEGORY_NAME = "CURRENT_SUBCATEGORY_NAME";

